name: career_rec
description: "A Career Recommender App!!."
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  percent_indicator : ^4.2.3
  dart_openai: ^5.0.0
  http: ^1.1.2
  url_launcher: ^6.2.1
  flutter_spinkit: ^5.2.0
  file_picker: ^5.2.6
  chat_bubbles: ^1.5.0
  cloud_firestore: ^4.13.5
  animated_notch_bottom_bar: ^1.0.1
  carousel_slider: ^4.2.1
  syncfusion_flutter_pdf: ^20.4.54
  firebase_database: ^10.4.0
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  video_player: ^2.8.2
  google_sign_in: ^6.2.1
  share_plus: ^7.2.0
  firebase_storage: ^11.5.6
  image_picker: ^1.0.5
  flutter_inappwebview: ^6.0.0
  flutter_markdown: ^0.6.18+2
  markdown_widget: ^2.3.1
  flutter_tts: ^3.8.0
  adaptive_theme: ^3.4.1
  speech_to_text: ^6.5.1
  settings_ui: ^2.0.2
  image: ^4.1.3
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.8
  cached_network_image: ^3.3.1
  camera: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
 
  assets:
    - assets/
    - assets/data/
    - assets/images/
    - assets/icons/
    - assets/icons/category/